config/routes.rb
Flashcards::Application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :decks do
    resources :cards, except: :index
  end
  root to: 'high_voltage/pages#show', id: 'home'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  attr_accessible :back, :front
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  belongs_to :user
  attr_accessible :name

  def to_param
    name
  end

  def as_json(options={})
    { name: name }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
  attr_accessible :email

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate
    if cookies[:user_id].blank?
      redirect_to new_session_path
    end
  end

  def current_user
    if cookies[:user_id]
      user_id = cookies.signed[:user_id]
      User.where(id: user_id).first
    end
  end
  helper_method :current_user

  def sign_in(user)
    cookies.signed[:user_id] = user.id
  end

  def signed_in?
    current_user
  end
  helper_method :signed_in?
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @deck = find_deck
    @card = find_card
  end

  def new
    @deck = find_deck
    @card = @deck.cards.new
  end

  def create
    @deck = find_deck
    @card = @deck.cards.create(params[:card])
    redirect_to @deck
  end

  def edit
    @deck = find_deck
    @card = find_card
  end

  def update
    @deck = find_deck
    @card = find_card
    @card.update_attributes(params[:card])
    redirect_to @deck
  end

  def destroy
    @deck = find_deck
    card = find_card
    card.destroy
    redirect_to @deck
  end

  private

  def find_deck
    current_user.decks.find(params[:deck_id])
  end

  def find_card
    @deck.cards.find(params[:id])
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :authenticate
  respond_to :html, :json

  def index
    @decks = current_user.decks
    respond_with @decks
  end

  def show
    @deck = current_user.decks.where(name: params[:id]).first
    respond_with @deck
  end

  def new
    @deck = current_user.decks.new
  end

  def create
    @deck = current_user.decks.new(params[:deck])
    @deck.save
    redirect_to decks_path
  end

  def edit
    @deck = current_user.decks.find(params[:id])
  end

  def update
    @deck = current_user.decks.find(params[:id])
    @deck.update_attributes(params[:deck])
    redirect_to deck_path(@deck)
  end

  def destroy
    @deck = current_user.decks.find(params[:id])
    @deck.destroy
    redirect_to decks_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(email: params[:session][:email]).first

    if user
      sign_in user
      redirect_to decks_path
    else
      render :new
    end
  end

  def destroy
    cookies.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to decks_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= form.label :front %>
<%= form.text_field :front %>
<%= form.label :back %>
<%= form.text_field :back %>

app/views/cards/edit.html.erb
<%= form_for [@deck, @card] do |form| %>
  <%= render 'form', form: form %>
  <%= form.submit 'Edit' %>
<% end %>

app/views/cards/new.html.erb
<%= form_for [@deck, @card] do |form| %>
  <%= render 'form', form: form %>
  <%= form.submit 'Create' %>
<% end %>

app/views/cards/show.html.erb
<%= @card.back %>

<%= link_to 'Edit', edit_deck_card_path(@deck, @card) %>
<%= link_to 'Destroy', [@deck, @card], method: :delete, confirm: 'Are you sure?' %>

app/views/decks/edit.html.erb
<%= form_for @deck do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit 'Update' %>
<% end %>

app/views/decks/index.html.erb
<%= link_to 'New deck', new_deck_path %>

<ul>
  <% @decks.each do |deck| %>
    <li><%= link_to deck.name, deck %></li>
  <% end %>
</ul>

app/views/decks/new.html.erb
<%= form_for @deck do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit 'Create a deck' %>
<% end %>

app/views/decks/show.html.erb
<h1><%= @deck.name %></h1>

<%= link_to 'Edit', edit_deck_path(@deck) %>
<%= link_to 'Delete', @deck, method: :delete, confirm: 'Are you sure?' %>

<%= link_to 'Add a card', new_deck_card_path(@deck) %>
<ul>
  <% @deck.cards.each do |card| %>
    <li><%= link_to card.front, [@deck, card] %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcards</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if signed_in? %>
    <%= current_user.email %>
    |
    <%= link_to 'Sign out', session_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign up', new_user_path %>
    <%= link_to 'Sign in', new_session_path %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to my flashcard app!</h1>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <% if @user.errors.any? %>
    <h3><%= pluralize @user.errors.messages.count, 'error' %> prevented this user from being saved.</h3>
    <div>
      <ul>
      <% @user.errors.messages.each do |field, messages| %>
        <% messages.each do |message| %>
          <li><%= "#{field.capitalize} #{message}." %></li>
        <% end %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :email %>
  <%= form.text_field :email %>
  <%= form.submit 'Sign up' %>
<% end %>